### ISSUE TITLE
Look up tables: Create endpoint from PR

### ISSUE THREAD

**Issue by andreievg** [openmsupply/conforma-server#328]
Wanted to merge lookup table codes for next demo, plus some PR change requests were not being addressed (commits were being added but not related to change requests), so wanted to manage it in a more stricter way:

- [x] - https://github.com/openmsupply/application-manager-server/pull/286#issuecomment-818622297 (only use underscore for variables with getter, rename `_lookupTableModal`
- [x] - https://github.com/openmsupply/application-manager-server/pull/286#discussion_r615511491 (remove destructuring of single array into a single array
- [x] - https://github.com/openmsupply/application-manager-server/pull/286#pullrequestreview-638387423 (shouldn't need to supply ID of rows when importing new CSV)
- [x]  - https://github.com/openmsupply/application-manager-server/pull/286#discussion_r612046890 (Simplify updateFiledMaps logic and extract it to helper function)
- [x] - https://github.com/openmsupply/application-manager-server/pull/286#discussion_r616221367, https://github.com/openmsupply/application-manager-server/pull/286#discussion_r616221494 (don't use await in combination with callbacks, `await` is meant to simplify callback logic)
- [x] - https://github.com/openmsupply/application-manager-server/pull/286#discussion_r616227077 (simplify validation, don't need `lookupTableNameValidator`, rely on front end not allowing tables with same name being created and catching postgres error)
- [x] - https://github.com/openmsupply/application-manager-server/pull/286#discussion_r622641487 Simplify key text code block for create and update rows
- [x] - https://github.com/openmsupply/application-manager-server/pull/286#discussion_r622644539 Remove Concrete<T> type created to make all properties required

**Comment by sworup** [comment]
> * [#286 (comment)](https://github.com/openmsupply/application-manager-server/pull/286#issuecomment-818622297) (only use underscore for variables with getter, rename `_lookupTableModal`

Resolved with 0507d9b

**Comment by sworup** [comment]
> * https://github.com/openmsupply/application-manager-server/pull/286#pullrequestreview-638387423 (shouldn't need to supply ID when importing)

> I've noticed that ID is required for import, and if ID exists it tried to update (i think previously you did a lookup query to decide if update or insert, but it was done while parsing csv, which I wasn't a fan of).
> 
> To keep it simple and get the PR merged quickly can we do this:
> 
> * for import, fail validation if `ID` exists with message "ID is auto generated when importing new lookup table, please rename or remove this column"
> * for update, has to have `ID` field (as it is now)
>   
>   * if `ID` is blank insert (as it is now)
>   * Otherwise update, 'returning ID', if no rows are returned insert

@andreievg I got a bit confused with this instruction.

For Lookup table structure id is not required to create a table structure. The endpoint is `lookup-tables/import`. 
`Id` is required for the update as in `lookup-tables/<structure_ID>/import`.

For rows ID can either be blank or value and it will create if id is blank and update if it has value.

Did you mean not to require id for update? In that case I would have to search by `table name`. I would prefer ID though.
