### ISSUE TITLE
Outcome improvements

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#556]
I originally started by commenting on a previous issue [here](https://github.com/openmsupply/application-manager-web-app/issues/903#issuecomment-899958966), but I thought it would be easier to make a new issue summarising the *requirements* of the Outcomes functionality in one place before we figure out an implementation.

Here are the things I think we need:

- ease of config: A new "Outcome" (i.e. a <outcome>_application_join table is created), should automatically have an entry in the outcomes list and be able to display basic data in table and detail view without any config. Config should just be for refining/improving/filtering the displays
- simpler way to define what columns show up in table and details view (include/exclude lists)
- robust against config errors (missing fields, etc.)
- default "text" display -- either the "text" field of the stored value, or the text itself. (and should have some way to respect line breaks, either Markdown or interpret `\n` correctly)
  - should be a default display for all common types, including Date, so can display in table without needing a SummaryView component (dates are the main use case for this, since ISO strings are no good in UI)
- permissions-based "layouts" -- groups of columns (as per above include/exclude lists) that are associated with permissionsNames. E.g for "User" outcomes, Admin might see all columns, whereas a regular user only sees name and username. Or can only see users associated with their own company.
- more flexibility over what can be displayed in a single column, i.e. we should be able to combine columns, for example, if we have 3 address fields (street, town, district), they should be able to be displayed in a single "address" fields combined. To do this we'd need access to more than just the current field value. My suggestion: when saving an outcome record, we also have an additional column which saves the whole "responsesByCode" object as JSON, and this is passed to display components for object lookups
- more flexibility in querying values for columns (not just fields in the outcome table). For example, in the Organisations outcomes, we should be able to display a list of users associated with the organisation in the outcome details, which would require a *query* in a column definition, not just a field. I like the idea of using the "SummaryView" components as the basis for displaying outcome details, but it'd be good to have more control over what we can send to a component.
- Should be able to export/import Outcome configs with templates (they really are an integral part of a template -- how to display the collected data), and we may want to have tighter associates between them (such as template_id in outcome_display table, or maybe just "code"?)
- Table list should be searchable, sortable and filterable, just like Applications list (in fact, we should be using a lot of the same core functionality if possible)
- Layout improvements:
  - table view should be basically the same as the Applications List (including filters, etc.)
  - detail view should be basically the same as application Summary page (vertical list, one component per line)
- (eventually) a UI to configure all the above, but let's get the design and implementation sorted first

### Basic idea

Outcome data will be served by a new GET endpoint (`/outcomes`), so the front-end won't have to do any logic to figure out what to show, or generate dynamic queries by querying the schema, etc. All that logic will be handled by the back-end, and will serve outcome data as JSON objects based on permissions and configs. This is instead of directly querying GraphQL from front-end, as we want to be able to have permission-based "layouts" (groups of defined columns), and row-level permissions alone will make this too complex. Essentially, the back-end endpoint will take care of figuring out which columns to return, and the existing row-level permissions will deal with what rows are retrieved (the JWT will be passed along to the endpoint's own database querying). The back-end can also perform complex evaluations on "special" columns, too.

~~The endpoint will query the database using SQL queries (rather than GraphQL), which will be much simpler for the kind of logic that will need to be performed on the resulting data (with include/exclude lists, etc.)~~ The endpoint will make SQL queries to determine schema (available columns etc), which will be dynamically built into GraphQL queries which are run with user's original JWT header (so we get row-level permissions)

In the front-end the Outcome tables can work essentially the same as the applications list, with the same filtering options, etc. The "Details" view will basically be the same as the Summary page (with maybe some horizontal "grid" layout -- TBD)

#### `outcome_display` table

- `id`, `table_name`, `title`, `code` -- same as current (remove `plural_table_name`)
- `permission_names` -- array of permission names, any of which allow the user to see the fields returned by the following four columns (default NULL = everyone can see):
- `table_view_include_columns` -- array of column names to include in table-view display (default NULL = show all)
- `table_view_exclude_columns` -- array of column names to exclude in table-view display (subtracted from "include" list) (default NULL)
- `detail_view_include_columns` / `detail_view_exclude_columns` -- same as previous two, but applied when in Details view
- `detail_view_header_column` -- when in Details view, the value of this column will be shown as the Details page "Header" (note: if a column of that name can't be found, the value itself will be shown, i.e. if the value here is "Entity" and there is no "entity" column found, the Header will just be "Entity" for all items of this view)
- `priority` -- (default 1). An integer. When the API is returning multiple layouts merged together, if they have different Titles or Header columns, the one with the highest priority will be used. Normally, this won't matter, but this provides a mechanism to specify if required (e.g. If the public "users" list was called "Users" and the admin users list was called "Users (Restricted View)", we can assign a higher priority to the latter so its title gets used when merging.
- `show_linked_applications` -- (default: true). We probably don't want to allow low-level or public users to access linked applications, in which case set to `false` for those layouts
- ~~`display_type` -- either `table`, `detail`, or `null`. Most of the time this is not required (default NULL = both). It would be expected that normally a field would display the same in both table and details view, the main difference between the two views would just be *which* columns are displayed. However, in the occasional case that you want them to be different, you'd make two different "layouts" with the same permissionNames, one with display_type "table",  one "detail", and create different "column_definition" entries (below) each linking to a different entry in this table.~~ (Replaced by `column_name` in subsequent table

In the simplest case, an outcome table can just have a single entry, with `table_name`, `title`, and `code` only -- this will display all fields of the table to all users, using default display functionality. (but row-level permissions still applied)

A more involved example:
- permission name "generalApply" for the "user" table, specifies columns "first_name, last_name" included
- permission name "manageCompany" for the "user" table has "NULL" included (ie. show all) and "password_hash" in the exclude list
- therefore, a basic user will see a list of first and last names when querying the "user" outcome table (and row-level permissions will restrict the entries, probably limited to their own company, say)
- a company "owner" (with "manageCompany") will see a user table will all fields except password hash
- in the case when a user has permissions for multiple column definition sets (henceforth: "Layouts"), the returned column set will be the *union* of all allowed columns (using priority for Title and Header as per above)

In a simple case, the above is all that is needed for both Table and Details display. If named column exists on the table in question, by default it will be displayed as a basic type (text, number, simple date) with no further clarification necessary. Further specification is only required if the column names (above) require one of the following:
- the "title" of the column needs to be something other than the (case-converted) field name
- the contents of the field are a complicated object that needs specific display instructions (like a SummaryView plugin component)
- the contents of the field require more detailed formatting definition (e.g. Markdown processing, or Date formatting)
- the column is not actually the name of a single column on the table, but instead has a complex "query" definition (which could be a concatenation of multiple columns, or a further database query (via evaluator expression))

For column names meeting this criteria, further definitions are detailed in the `outcome_display_column_definition` table:

#### `outcome_display_column_definition` table

- `id`
- ~~`outcome_display_id` -- FK ref to above table entry, says what Outcome table it's part of~~ (replaced by `column_name` and `table_name`)
- `table_name` -- name of table
- `column_name` -- the name of the column in "table_view_include_columns" or "detail_view_include_columns" to match with, so we know where in the column order this definition field should go. Also allows the same definition description to match to multiple layouts (from the same table). Any column names that are not exact fields on the outcome table are basically a "code" for matching to a column_definition description 
  - _Note: `table_name` and `column_name` must be unique (in combination)_
- `title` -- custom title for the column (default NULL = case-converted field name, as above)
- `element_type_plugin_code` -- if specified, the front-end will know to pass the whole returned value into a "SummaryView" component of this type for display. In these cases, the saved value on the field should correspond to the whole "response" object expected by that plugin type.
`additional_formatting` -- an extensible JSON field for adding any further specifications for the front-end to display the data. Current suggested fields are:
    - `markdown` -- (boolean, default false) tells the front-end to render output with Markdown processing (only relevant for "string" outputs)
    - `date_format` -- if specified, front-end should assume the value is an ISO date string, this field provides a Luxon date-format preset (https://moment.github.io/luxon/#/formatting?id=presets) to render it as e.g. "DATE_TIME_FULL", "DATE_MED", "TIME_SIMPLE" (could maybe also be achieved using the "DatePicker" element, maybe we don't need both?)
*EDIT: Suggest combining these two fields into a single json field called `additional_formatting`. That way we don't have to change the schema if we add more formatting parameters later on*
- `value_expression` -- this field is only required for "custom" columns -- i.e. columns that don't match to specific fields in the outcome table. Should be in the form of an evaluator expression. The "object" passed in for objectProperties will be a single object containing every field of this current outcome table record (so evaluator can combine values from multiple fields, for example). Or it could be a further database query, or even API lookup -- anything the expression evaluator can do.

#### `/outcomes`

Simple query to get a list of all available Outcome tables. Will deduce permissionNames from JWT, then find the matching records (layouts) in `outcome_display`, then returns the ones that the requesting user is allowed access to, as an array of distinct`{ title, code, id}` objects (using priority as above)

Used by the front-end to populate the "Outcomes" menu.

No url query parameters necessary

#### `/outcomes/table/<tableName>?<queries>`

For fetching data for a particular outcome table for "table" view display.

1. Server first deduces which "columns" the user is allowed, based on permissionNames (from JWT) and the include/exclude lists in `outcome_display`
2. Looks for which of those "columns" have special definitions in "outcome_display_column_definition"
  - makes a "master" list of returning columns with all details of where to fetch their information (either from an outcome field, or an evaluator expression), and their formatting information
3. Fetches ALL columns from Outcome table (using GraqhQL with user's JWT), because even fields that are not being returned can be referenced in evaluator expressions
4. Iterate over "master list", building a response object with either field values or evaluated values, and all column definitions (in a "header" row). (Note: for evaluation expressions, the passed-in object (for "objectProperties") is all the complete object (_all_ fields) for the current record)
3. Return object presents tabular data in following shape:
```
{
  tableName: <table>,
  title: <Title for UI>,
  code: <code>,
  headerRow: [
                {
                columnName: <name>,
                title: <column title for UI>,
                isBasicField: <if column is an outcome field (true) or evaluated expression(false),
                dataType: <postgres data type -- only present for "basic" fields>,
                formatting: {
                  elementTypePluginCode: <code>,
                  elementParameters: <json>,
                  markdown: <true/false>,
                  dateFormat: <Dateformat>
                  (Note: properties on formatting missing if they are undefined)
                    }
              }
               ... (for each column)
             ],
  tableRows: [
               {
                  id: <id>,
                  rowValues: [
                    ...values (one per column in header row)
                  ],
                  item: {
                   ...<column: value> pairs (same as rowValues, but as Object)
                  }
               },
                ... (for each record returned)
            ],
  totalCount: <number-of-total-results-for-table> (for pagination calculations)
}
```

**Query parameters**:

- `first` -- number of records to return (default 20?)
- `offset` -- starting at what number record (default 0)
- `orderBy` --  "columnName" (default ID?)
- `ascending` -- true/false (default true)

**TO-DO: queries for filter/search -- should they be constructed in front-end or here?**

#### `/outcomes/table/<tableName>/item/<recordID>`

For fetching data for a particular record for "details" view display.

Similar logic to above, but just for one record (and looking at "detail" columns rather than "table" column lists). We also need to fetch the linked applications from the outcome_join table. 

Return object is:

```
{
 tableName: <table>,
 id: <id>,
 header: {
        value, columnName, isBasicField, dataType, formatting:{} (as above, but with value and formatting info combined, since its only one entity)
    },
 columns: [ list of column names,... ]
 displayDefininitions: {
   <columnName>: {title, isBasicField, dataType, formatting:{} (as above)},
   ...for each column/field
 },
 item: {
   <columnName>: <value>,
   ...for each column/field
 }
 linkedApplications: [ {id, name, serial, templateName, templateCode, dateCompleted}, ... ]
}
```

### Notes / To-Do

- This spec assumes that data is already in system, it doesn't deal with how to define policies for outcome tables. That's a separate problem (which does need addressing)
- Haven't made any spec around importing/exporting outcome definitions with templates. That can be worked out once this module is implemented.
- Assuming that, once this spec is implemented, front-end design will be fairly obvious (albeit still with some complications), so haven't put much implementation detail about that here.
- Creating outcome tables that have a proper "relational" structure, either through multiple tables or through searchable JSON fields not discussed here, but needs to be kept in mind (had brief discussion with Andrei)
- There's more that needs to be sorted out with regards to the "formatting" aspects of the API response. Will need to re-visit when implementing front-end.

### Development

**Back-end**:

- [x] Update schema and implement initial "/outcomes" endpoint #564 ([PR for first three](#573)
- [x] Implement `/outcomes/table` endpoint #565
- [x] Implement `outcomes/table/item` endpoint #566
- [ ] Make sure Snapshots handle outcome tables correctly #567

**Front-end**:
- [x] Re-implement current Outcomes display using new API, and rendering cells with specified formatting options (including default for basic types) https://github.com/openmsupply/application-manager-web-app/issues/976 ([PR1](https://github.com/openmsupply/application-manager-web-app/pull/983)) [PR2](https://github.com/openmsupply/application-manager-web-app/pull/984)
- [ ] Update table view to be more like Applications list, with Filters, sorting and search and pagination https://github.com/openmsupply/application-manager-web-app/issues/977
- [x] Update details view to be more like Summary page https://github.com/openmsupply/application-manager-web-app/issues/978

**Further development**
- [ ] Come up with solution for associating permission policies with new Outcome #568
- [ ] Import/Export Outcome definitions with templates #569
- [ ] Template Builder -- add UI for customising outcomes
- [ ] Investigate more complex relational outcome data #570
- [ ] Add a public page for accessing publicly available Outcome layouts (outside AuthenticatedContent)

**Comment by CarlosNZ** [comment]
Reminder: need to add:
- Linked applications
- Queries will need to be GraphQL (not SQL) as backend uses Postgres user for SQL (so won't enforce row-level permissions)

**Comment by CarlosNZ** [comment]
@andreievg -- it occured to me that it's like that we'd want to often have the same "column_definition" description for the same field across multiple layouts for the same table, which means linking them to a specific "outcome_display" record would mean you'd a lot of duplication (which could be fairly complex). So have replaced the FK ref to "outcome_display" with a `table_name` / `column_match` combo, so the same column definition can connect to different layouts, if the "column name" is used in multiple layouts. 

So essentially, the column names in "include_list" are either a) names of fields on the original outcome table, or b) "codes" for matching to column_definition records. (This also solves the problem of knowing where in the column order a column_definition goes, and makes a more explicit link between "column_names" (or codes) and "column_definitions", which I think is better.

**Comment by andreievg** [comment]
> @andreievg -- it occured to me that it's like that we'd want to often have the same "column_definition" description for the same field across multiple layouts for the same table, which means linking them to a specific "outcome_display" record would mean you'd a lot of duplication (which could be fairly complex). So have replaced the FK ref to "outcome_display" with a table_name / column_match combo, so the same column definition can connect to different layouts, if the "column name" is used in multiple layouts.

> So essentially, the column names in "include_list" are either a) names of fields on the original outcome table, or b) "codes" for matching to column_definition records. (This also solves the problem of knowing where in the column order a column_definition goes, and makes a more explicit link between "column_names" (or codes) and "column_definitions", which I think is better.

> (Have updated the spec)

Ok, sounds good, i think. (althought I think it's vary rare case, and would require minimum repetition).

Can column_match just be column_name ?

**Comment by CarlosNZ** [comment]
> Can column_match just be column_name ?

Yes, I guess so.

**Comment by CarlosNZ** [comment]
> althought I think it's vary rare case, and would require minimum repetition

I think a common use case would be -- you have an outcome layout that can be viewed by a wide group of people, and say it has 2 or 3 fairly complex "custom" columns. Then your realise (for example), that public viewers shouldn't see the "linked applications" in details view (but everything else should be the same). So you can quickly create a new "layout" for public, with that one small change, but you DON'T have to re-define all the custom columns -- as long as they point to the same table and columnNames, they'll continue to work fine.

**Comment by CarlosNZ** [comment]
All done and working nicely :)
