### ISSUE TITLE
Backup/snapshot improvments to use pg_dump/pg_restore

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#909]
After quite a bit of investigation, I've figured out how to get pg_dump/pg_restore to work without the errors we were getting whenever we've tried it in the past. This will make things so much faster -- we can load the whole Angola database in less than a second!

The bad news is, we need to refactor quite a few of the functions to put the schema prefix `public` in the FROM statements. We've done it for quite a few already, but there are plenty of exceptions. The reasons for this are pretty technical, and I don't fully understand it, but you can get a bit of an idea of it from [here](https://stackoverflow.com/questions/56729192/pg-restore-fails-when-trying-to-create-function-referencing-table-that-does-not#comment121636171_58274381) (The problem described in that issue is the problem we were having with pg_restore.)

This would mean our migration script getting a bit out of control with recreating all the functions that already exist, so I suggest we do something like I mentioned to Fergus in [this comment](https://github.com/openmsupply/conforma-server/pull/903#pullrequestreview-1139793684) (3rd bullet point).

So, my suggested workflow for getting pg_dump-based snapshots and backups working is as follows:

- [x]  **Part 1 (Issue #910)** (PR: #914)
  - move all function (and trigger) definitions out of the individual .sql script files and put them all in a single file at the end of the sequence.
  - refactor them to add `public.` schema prefix to the "FROM" clauses
  - remove all function definitions (except DROPs) from the migration script
  - at the end of the migration script call the functions.sql (the new one we've just created) we just read and execute the "CREATE OR REPLACE" for ALL functions and triggers. Yes, this does mean that we drop and re-create all functions for every migration, but it's actually a pretty trivial operation if we're only doing it for version upgrades. And it will save us a lot of hassle when we have to update functions and not have to define them in two different places like we're currently doing. And will stop the migration script getting ridiculous like it currently is (it will be a lot smaller after this, even though it's doing the same amount of work)

- [ ]  **Part 2 (Issue #911)** (PR: #916)
  - Update the useSnapshot/takeSnapshot scripts to use pg_dump and pg_restore when doing whole database snapshots. We should still keep the current mechanism, but the default behaviour will be the new one. I'll need to figure out exactly how the system decides which mechanism to use -- it might be better to just have two options: "Full snapshot", which will use pg_dump; and "template export", which uses the current mechanism, and nothing in between. This will need a bit of looking at to see which is the most straightforward way to migrate the method.
  - Make sure the Snapshot import/export UI correctly uses the new pg_dump method
  - Make sure the template import/export UI corrrectly uses the current method
  - Check that old snapshots are still compatible and that the scripts for setting up a new database still work correctly (the import process will need to check if the snapshot folder has a ".dump" file in it, or a "snapshot.json" and act accordingly.

- [ ]  **Part 3 (Issue #912)** (PR: #918)
  - Write a backup script and simple scheduler to create automated backups using this new system, as described in [this issue](https://github.com/openmsupply/conforma-server/issues/881#issue-1396929676) (Option 2)

- [ ]  **Part 4 (Issue #917)** (PR: #920)
  - Configure Docker-compose to be able to map a user-defined host folder to a container volume/bind-mount

**Comment by CarlosNZ** [comment]
I think using pg_restore might also mean we don't have to run the annoying "reset_serial.sql" functions to fix the serial sequences, so that's an added bonus. Not sure.
