### ISSUE TITLE
Transitition to using built-in "core actions"

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#981]
Just doing a checklist so we remember everything and can keep track of who's done what.
- [x] Approve and merge into `feature/core-actions`: #976 
- [x] Approve and merge into `feature/core-actions`: #978 
- [x] Approve and merge into `feature/core-actions`: #980 
- [x] Make a test build (v0.5.0-4) and put on demo server
- [x] Merge `feature/core-actions` into `develop`
- [x] Update "core_templates" templates to remove core actions from config PR: #995
- [x] Make new build (let's call this v0.5.0 final)
- [x] Update **Fiji** snapshot and load to Fiji demo server (50004)/upgrade to 0.5.0
  - [x] Remove all "core actions" from all template configs
  - [x] Update "serial pattern" field for templates that need it (get from original "ON_APPLICATION_CREATE" action), test that it works
- [x] Update **Angola** snapshot and load to Angola demo server (50008)/upgrade to 0.5.0
  - [x] Remove all "core actions" from all template configs
  - [x] Update "serial pattern" field for templates that need it (get from original "ON_APPLICATION_CREATE" action), test that it works
- [x] Upgrade "live" servers to v0.5.0 and install fixed snapshots

**Comment by CarlosNZ** [comment]
Done 🥳
